create table role
(
    name varchar(255) not null,
    primary key (name)
);

create table role_title
(
    role_name varchar(255) not null,
    text      varchar(255) not null,
    language  varchar(40)  not null,
    primary key (role_name, language)
);

create table user
(
    id               bigint generated by default as identity,
    encoded_password varchar(255) not null,
    full_name        varchar(255) not null,
    username         varchar(255) not null,
    primary key (id)
);

create table user_role
(
    role_name  varchar(255) not null,
    user_id    bigint       not null,
    expires_at timestamp    not null,
    name       varchar(255) not null,
    primary key (role_name, user_id)
);

alter table role_title
    add constraint FK_role_name_on_role
        foreign key (role_name)
            references role;

alter table user_role
    add constraint FK_name_on_role
        foreign key (name)
            references role;

alter table user_role
    add constraint FK_user_id_on_user
        foreign key (user_id)
            references user;