name: backend_user
on: 
  push:
    paths:
    - '.github/**'
    - 'backend/user/**'
jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/user
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '15'
        java-package: jdk
        architecture: x64
    - run: ./gradlew test