name: frontend
on: 
  push:
    paths:
    - '.github/**'
    - 'frontend/**'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install packages
        run: npm install
      
      - name: Lint workspace and projects
        shell: bash
        run: npm run lint

      - name: Run Tests
        shell: bash
        run: npm run test